# Generated by Django 5.1.3 on 2024-12-13 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosUser', '0002_domicilio_domicilio_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio_ruta',
            name='info',
        ),
        migrations.RemoveField(
            model_name='domicilio_ruta',
            name='user',
        ),
        migrations.DeleteModel(
            name='Datos_personal',
        ),
        migrations.DeleteModel(
            name='Domicilio_ruta',
        ),
    ]
