# Generated by Django 5.1.5 on 2025-02-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUser', '0003_remove_domicilio_ruta_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='municipio',
            field=models.CharField(choices=[('E', 'Ekmul'), ('T', 'Tixkokob'), ('N', 'Nolo')], default='E', max_length=20),
        ),
    ]
