# Generated by Django 5.1.3 on 2025-02-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUser', '0005_alter_domicilio_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='municipio',
            field=models.CharField(choices=[('E', 'Ekmul'), ('T', 'Tixkokob'), ('N', 'Nolo')], default='E', help_text='Disponible solo Ekmul', max_length=100),
        ),
    ]
