# Generated by Django 5.1.3 on 2025-01-03 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('datosUser', '0003_remove_domicilio_ruta_info_and_more'),
        ('productos', '0002_producto_descripcion_producto_nombre_producto_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_entrega', models.DateTimeField()),
                ('tipo_pedido', models.CharField(choices=[('D', 'Domicilio'), ('E', 'Express'), ('T', 'Tienda')], max_length=1)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estatus', models.CharField(choices=[('E', 'Espera'), ('C', 'En curso'), ('F', 'Entregado')], max_length=1)),
                ('domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosUser.domicilio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.PositiveIntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='carrito.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
