# Generated by Django 5.1.3 on 2025-01-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_pedido_pedido_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido_producto',
            old_name='unidad',
            new_name='cantidad',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estatus',
            field=models.CharField(choices=[('X', 'Cancelado'), ('E', 'Espera'), ('C', 'En curso'), ('F', 'Entregado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='horario_entrega',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('D', 'Domicilio'), ('E', 'Express'), ('T', 'Tienda')], default='D', max_length=1),
        ),
    ]
