# Generated by Django 5.1.3 on 2025-01-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_rename_unidad_pedido_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocarrito',
            name='seleccionado',
            field=models.BooleanField(default=True),
        ),
    ]
