# Generated by Django 5.1.3 on 2025-01-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_productocarrito_seleccionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocarrito',
            name='seleccionado',
            field=models.BooleanField(default=False),
        ),
    ]
