# Generated by Django 5.1.3 on 2025-01-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_alter_productocarrito_seleccionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estatus',
            field=models.CharField(choices=[('X', 'Cancelado'), ('E', 'Espera'), ('C', 'En curso'), ('F', 'Entregado')], default='E', max_length=1),
        ),
    ]
