# Generated by Django 5.1.5 on 2025-02-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_alter_pedido_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pedido',
            field=models.CharField(choices=[('D', 'Domicilio'), ('E', 'Express'), ('T', 'Tienda')], default='D', help_text='Disponible solo Domicilio', max_length=100),
        ),
    ]
