# Generated by Django 5.1.5 on 2025-02-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0008_pedidorepartidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidorepartidor',
            name='pedidos',
            field=models.JSONField(default=list),
        ),
    ]
