# Generated by Django 5.1.5 on 2025-02-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0009_alter_pedidorepartidor_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidorepartidor',
            name='pedidos',
            field=models.JSONField(default=dict),
        ),
    ]
