# Generated by Django 5.1.5 on 2025-02-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0010_alter_pedidorepartidor_pedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidorepartidor',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='pedidorepartidor',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.pedido'),
        ),
    ]
