# Generated by Django 5.1.3 on 2024-12-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('existencia', models.DecimalField(decimal_places=0, max_digits=9)),
                ('estado', models.BooleanField(help_text='disponibilidad')),
            ],
        ),
    ]
