# Generated by Django 5.1.3 on 2025-01-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_descripcion_producto_nombre_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
