# Generated by Django 5.1.3 on 2025-01-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_descripcion_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='descripcion', help_text='Descripsion que ayude a los clientes a saber que estan comprando', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='nombre', help_text='Nombre del Producto', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('u', 'Unidad'), ('p', 'Paquete'), ('m', 'Menudeo')], default='u', help_text='Tipo de producto', max_length=1),
        ),
    ]
