# Generated by Django 5.1.3 on 2025-01-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortilleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_tortilleria',
            name='imagen',
            field=models.ImageField(upload_to='informacion/'),
        ),
    ]
