# Generated by Django 5.1.5 on 2025-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tortilleria', '0004_rename_historialempleados_historialempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialempleado',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
